apiVersion: v1
kind: Service
metadata:
  name: notasite
  namespace: apps
  labels:
    app: notasite
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: notasite
