version: "3"
services:
  gitlab:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    container_name: infra_gitlab
    ports:
      - 80:80
      - 443:443
      - 2223:22
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    deploy:
      resources:
        limits:
          memory: "5G"
          cpus: "4"
        reservations:
          memory: "4G"
          cpus: "3"

  db:
    image: postgres:10
    restart: always
    container_name: infra_postgres
    environment:
      POSTGRES_PASSWORD: "SomeSecurePassword"
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: "3G"
          cpus: "2"
        reservations:
          memory: "2G"
          cpus: "1"