version: "3"
services:

  haproxy:
    build: .
    container_name: infra_haproxy
    ports:
      - 80:80
      - 443:443
      - 81:81
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: unless-stopped
    networks:
      infra_network:
        aliases:
          - infra_haproxy
    

  gitlab:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    container_name: infra_gitlab
    ports:
      - 8080:80
      - 8443:443
      - 22:22
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      infra_network:
        aliases:
          - infra_gitlab
    deploy:
      resources:
        limits:
          memory: "6G"
          cpus: "4"
        reservations:
          memory: "4G"
          cpus: "3"

  db:
    image: postgres:10
    restart: always
    container_name: infra_postgres
    environment:
      POSTGRES_PASSWORD: "SomeSecurePassword"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "0.5"
        reservations:
          memory: "1G"
          cpus: "0.5"
    networks:
      infra_network:
        aliases:
          - infra_postgres

networks:
  infra_network: