version: "3"
services:

  haproxy:
    build: .
    container_name: infra_haproxy
    ports:
      - 80:80
      - 443:443
      - 81:81
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: unless-stopped
    networks:
      infra_network:
        aliases:
          - infra_haproxy
    # entrypoint: "haproxy"
    # command: "haproxy"
    

  gitlab:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    container_name: infra_gitlab
    ports:
      - 8080:80
      - 8443:443
      - 8022:22
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      infra_network:
        aliases:
          - infra_gitlab
    deploy:
      resources:
        limits:
          memory: "5G"
          cpus: "4"
        reservations:
          memory: "4G"
          cpus: "3"

  db:
    image: postgres:10
    restart: always
    container_name: infra_postgres
    environment:
      POSTGRES_PASSWORD: "SomeSecurePassword"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: "3G"
          cpus: "2"
        reservations:
          memory: "2G"
          cpus: "1"
    networks:
      infra_network:
        aliases:
          - infra_postgres

  pg_admin:
    image: dpage/pgadmin4
    container_name: infra_pgadmin
    restart: always
    ports:
      - 8880:80
    networks:
      infra_network:
        aliases:
          - infra_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

networks:
  infra_network: