gitlab_base_url              = "http://gitlab.kube.local/api/v4/"
keycloak_deployment_path     = "../configs/gitlab/infra/keycloak/deployment.yaml"
keycloak_service_path        = "../configs/gitlab/infra/keycloak/service.yaml"
keycloak_gateway_path        = "../configs/gitlab/infra/keycloak/gateway.yaml"
keycloak_virtualservice_path = "../configs/gitlab/infra/keycloak/virtualservice.yaml"
keycloak_application_path    = "../configs/gitlab/infra/applications/keycloak.application.yaml"
argocd_ssh_key               = "../configs/gitlab/ssh/gitlab.pub"