gitlab_base_url              = "http://gitlab.kube.local/api/v4/"
keycloak_deployment_path     = "../configs/keycloak/deployment.yaml"
keycloak_service_path        = "../configs/keycloak/service.yaml"
keycloak_gateway_path        = "../configs/keycloak/gateway.yaml"
keycloak_virtualservice_path = "../configs/keycloak/virtualservice.yaml"
