apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.kube.local:devops/argocd.git
    targetRevision: HEAD
    path: apps/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    istio-injection: enabled