apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.kube.local:devops/argocd.git
    targetRevision: HEAD
    path: infra/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra