# This patch allows insecure communication with ArgoCD. Without it, we would have to use HTTPS, which needs a certificate.
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        command: 
          - argocd-server
          - --insecure
      hostAliases:
        - ip: "10.0.2.2"
          hostnames:
          - "postgres.kube.local"
        - ip: "192.168.56.100"
          hostnames:
            - "argocd.kube.local"
            - "keycloak.kube.local"
