# This patch allows insecure communication with ArgoCD. Without it, we would have to use HTTPS, which needs a certificate.
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        command: 
          - argocd-server
          - --insecure