kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: keycloak
  name: keycloak
  labels:
    app: keycloak

spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:19.0.2
          imagePullPolicy: IfNotPresent
          args: ["start-dev"]
          ports:
          - name: http
            containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          ## volume mounts required when using H2 database
          # volumeMounts:
          #   - name: keycloak-data
          #     mountPath: /opt/jboss/keycloak/standalone/data
          # resources:
          #   requests:
          #     memory: "250Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "500Mi"
          #     cpu: "500m"
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: KEYCLOAK_USER
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: KEYCLOAK_ADMIN
            # - name: JAVA_OPTS_APPEND
            #   valueFrom:
            #     configMapKeyRef:
            #       name: keycloak
            #       key: JAVA_OPTS_APPEND
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: DB_VENDOR
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: POSTGRES_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: POSTGRES_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: POSTGRES_USER
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: POSTGRES_DATABASE
            - name: PROXY_ADDRESS_FORWARDING
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: PROXY_ADDRESS_FORWARDING
            - name: KEYCLOAK_LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: KEYCLOAK_LOGLEVEL
            - name: ROOT_LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: ROOT_LOGLEVEL
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_PASSWORD
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: POSTGRES_PASSWORD
              
      ## volume required when using H2 database
      # volumes:
      #   - name: keycloak-data
      #     persistentVolumeClaim:
      #       claimName: keycloak-pvc

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: keycloak
#   namespace: keycloak
#   labels:
#     app: keycloak
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: keycloak
#   strategy: 
#     type: "RollingUpdate"
#     rollingUpdate: 
#       maxSurge: 1
#       maxUnavailable: 1
#   minReadySeconds: 5
#   template:
#     metadata:
#       labels:
#         app: keycloak
#     spec:
#       containers:
#       - name: keycloak
#         image: quay.io/keycloak/keycloak:19.0.2
#         imagePullPolicy: Always
#         args: ["start-dev"]
#         env:
#         - name: KEYCLOAK_ADMIN
#           value: "admin"
#         - name: KEYCLOAK_ADMIN_PASSWORD
#           value: "admin"
#         - name: KC_PROXY
#           value: "edge"
#         - name: KEYCLOAK_FRONTEND_URL
#           value: "http://keycloak.kube.local/auth"
#         - name: DB_VENDOR
#           value: "postgres"
#         - name: DB_ADDR
#           value: "10.0.2.2"
#         - name: DB_PORT
#           value: "5432"
#         - name: DB_USER
#           value: "postgres"
#         - name: DB_PASSWORD
#           value: "SomeSecurePassword"
#         ports:
#         - name: http
#           containerPort: 8080
#         readinessProbe:
#           httpGet:
#             path: /realms/master
#             port: 8080