apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
type: Opaque
data:
  KEYCLOAK_PASSWORD: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  POSTGRES_PASSWORD: U29tZVNlY3VyZVBhc3N3b3Jk